[workspace]
git_tag_enable = true
git_tag_prefix = "v"
pr_draft = false
pr_labels = ["release"]
changelog_config = ".github/changelog.json"
changelog_include_pull_requests = true

[package]
semver_check = true
publish_allow = true
